
using UnityEngine;
using System.Collections.Generic;
using System;

//This class allows for deterministic random generation based on seed values
public class TerrainRandomizer : MonoBehaviour
{

	//Create a single random master seed from which all randomized layers are derived 
	private static int masterSeed =  new System.Random().Next (0, 1000000);


	//Pass in a seed value, get a predictable random number between 0 and 1 million
	public static float getRand (int seed)
	{
		UnityEngine.Random.seed = seed;

		return UnityEngine.Random.Range (0, 1000000);
	}

	//Pass in a seed value, get TWO predictable random numbers between 0 and 1 million,
	//Calls the previous method by passing in the seed parameter for the first number,
	//Then uses that result as a seed for the second number, all deterministic and predictable
	public static float[] getTwoRand (int seed)
	{
		float[] bothRandoms = new float[2];
		bothRandoms [0] = getRand (seed);
		bothRandoms [1] = getRand ((int)bothRandoms [0]);

		return bothRandoms;

	}

	//simply returns the master seed generated by the class upon initialization
	public static int getMasterSeed ()
	{
		return masterSeed;
	}

}



